export const people = [
  {
    id: 1,
    name: "Matheus Santos Carvalho",
    roles: ["Backend"],
    image: "",
    initials: "MC",
  },
  {
    id: 2,
    name: "João Pedro Almeida Felisberto",
    roles: ["Frontend"],
    image: "",
    initials: "JF",
  },
  {
    id: 3,
    name: "Pedro Higor De Freitas Campos",
    roles: ["Backend"],
    image: "",
    initials: "PC",
  },
  {
    id: 4,
    name: "Alícia Kathleen De Paula Ferreira",
    roles: ["Frontend"],
    image: "",
    initials: "AF",
  },
  {
    id: 5,
    name: "Yuri Fernandes Faustino Reis",
    roles: ["Frontend"],
    image: "",
    initials: "YR",
  },
  {
    id: 6,
    name: "Henrique Lucio Naves",
    roles: ["Designer"],
    image: "",
    initials: "HN",
  },
  {
    id: 7,
    name: "Vinicius Varoli Machado",
    roles: ["Frontend"],
    image: "",
    initials: "VM",
  },
  {
    id: 8,
    name: "Any Gabriely Lima Nascimento",
    roles: ["Fullstack"],
    image: "",
    initials: "AN",
  },
  {
    id: 9,
    name: "Eduardo Pereira Lima",
    roles: ["Frontend"],
    image: "",
    initials: "EL",
  },
  {
    id: 10,
    name: "Aleikson Rodrigues Silva Filho",
    roles: ["Fullstack"],
    image: "",
    initials: "AF",
  },
  {
    id: 11,
    name: "Emerson Gois Silva",
    roles: ["Frontend"],
    image: "",
    initials: "ES",
  },
  {
    id: 12,
    name: "Guilherme de Brito Tupinambá Melo",
    roles: ["Frontend"],
    image: "",
    initials: "GM",
  },
  {
    id: 13,
    name: "Wladimir Salgado Pereira",
    roles: ["Frontend"],
    image: "",
    initials: "WP",
  },
  {
    id: 14,
    name: "Tiago Carneiro Batista",
    roles: ["Fullstack", "Scrum Master"],
    image: "/tiago-carneiro-batista.webp",
    initials: "TB",
  },
  {
    id: 15,
    name: "Jackciel Felix Soares",
    roles: ["Backend"],
    image: "",
    initials: "JS",
  },
  {
    id: 16,
    name: "Luciano Guido dos Santos Silva",
    roles: ["Backend"],
    image: "",
    initials: "LS",
  },
  {
    id: 17,
    name: "Marcelo Felix Pereira",
    roles: ["Frontend"],
    image: "",
    initials: "MP",
  },
  {
    id: 18,
    name: "Felipe Rodrigo Gonçalves",
    roles: ["Backend"],
    image: "",
    initials: "FG",
  },
  {
    id: 19,
    name: "Cícero Wesley Bezerra Lima",
    roles: ["Frontend"],
    image: "",
    initials: "CL",
  },
  {
    id: 20,
    name: "Gabriel Caetano da Costa",
    roles: ["Frontend"],
    image: "",
    initials: "GC",
  },
  {
    id: 21,
    name: "Wandercley Johnny Silva Paulino",
    roles: ["Fullstack"],
    image: "",
    initials: "WP",
  },
  {
    id: 22,
    name: "Kauã Henrique Preto Amélio",
    roles: ["Frontend"],
    image: "",
    initials: "KA",
  },
  {
    id: 23,
    name: "Cândida Percilianno Celestino",
    roles: ["Frontend"],
    image: "",
    initials: "CC",
  },
  {
    id: 24,
    name: "Gabriela Alcântara Silva",
    roles: ["Backend"],
    image: "",
    initials: "GS",
  },
];

export const badgeVariants: { [key: string]: string } = {
  Frontend: "bg-green-500",
  Backend: "bg-red-500 text-neutral-50",
  Fullstack: "bg-blue-500 text-neutral-50",
  Default: "bg-yellow-500",
};
